# Generated by Django 4.0.6 on 2022-08-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=250, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('documento', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=250, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('documento', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('marca_veh', models.CharField(max_length=100)),
                ('color_veh', models.CharField(max_length=100)),
                ('documentacion_veh', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposdeServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_serv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.tiposdeservicios')),
            ],
        ),
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('colegio', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=100)),
                ('comentario_add', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.cliente')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.cliente')),
            ],
        ),
    ]
