# Generated by Django 4.0.6 on 2022-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clave',
            field=models.CharField(default='12345', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('S', 'Supervisor'), ('O', 'Operario')], default='O', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(default='u1', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
