# Generated by Django 4.0.6 on 2022-11-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0003_remove_proveedores_color_veh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='proveedores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.proveedores'),
            preserve_default=False,
        ),
    ]
