# Generated by Django 4.0.6 on 2022-11-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0004_comentarios_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('C', 'Cliente'), ('P', 'Proveedor')], default='C', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(default='planta/fotos/default.webp', upload_to='planta/fotos'),
        ),
    ]
