# Generated by Django 4.0.6 on 2022-11-22 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0007_remove_servicios_tipo_serv_servicios_caracteristicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.cliente'),
            preserve_default=False,
        ),
    ]
