# Generated by Django 4.0.6 on 2022-11-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0008_remove_comentarios_proveedores_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
