# Generated by Django 4.0.6 on 2022-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0009_delete_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='transportes/fotos/default.webp', upload_to='transportes/fotos'),
        ),
    ]
