# Generated by Django 4.0.6 on 2022-12-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0013_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
    ]
