# Generated by Django 4.0.6 on 2022-12-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0014_remove_vehiculo_foto_alter_cliente_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticiones',
            name='beneficiarios',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.beneficiarios'),
            preserve_default=False,
        ),
    ]
