# Generated by Django 4.0.6 on 2022-12-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0015_peticiones_beneficiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticiones',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
