# Generated by Django 4.0.6 on 2022-12-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0016_peticiones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticiones',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
    ]
