# Generated by Django 4.0.6 on 2022-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0017_alter_peticiones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
    ]
