# Generated by Django 4.0.6 on 2022-12-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportesEscolaresSena', '0018_vehiculo_actual_vehiculo_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='transportesEscolaresSena.cliente'),
        ),
    ]
